name: 'AWS Login'
run-name: ${{ github.actor }} is AWSing 
on:
  [push]
permissions:
  id-token: write
jobs:
  AWS-Login-Jobik:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-1
          role-to-assume: "arn:aws:iam::455170233623:role/${{ vars.AWS_ROLE_TO_ASSUME }}"
          role-session-name: blax_tns_oidc_session

      - name: identity
        run: aws sts get-caller-identity
        shell: bash
 
      - name: s3 check
        run: aws s3 ls s3://
        shell: bash

##      - name: Login to Amazon ECR
##        id: login-ecr-blax
##        uses: aws-actions/amazon-ecr-login@v1
##
##      - name: Build, tag, and push docker image to Amazon ECR
##        env:
##          REGISTRY: ${{ steps.login-ecr-blax.outputs.registry }}
##          REPOSITORY: tns-blax-repo/blex
##          IMAGE_TAG: ${{ github.sha }}
##        run: |
##          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
##          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
##
