name: Publish Docker image
run-name: builder is building
on:
  [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout blax-a repo
        uses: actions/checkout@v3
        with:
          path: 'blax-a/'
          ref: 'v0.0.2'
          repository: 'tskuit/blax-a'

      - name: Checkout blax-b repo
        uses: actions/checkout@v3
        with:
          path: 'blax-b/'
          ref: 'v0.0.2'
          repository: 'tskuit/blax-b'


##      -
##        name: Build and push
##        uses: docker/build-push-action@v4
##        with:
##          tags: blax/app:latest
##
